"use client";

import { useMemo, useState } from "react";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/card";
import { Disclosure } from "@/components/ui/disclosure";
import { Stat } from "@/components/ui/stat";
import { USFleetMap } from "@/components/us-fleet-map";
import { DeviceDrilldown } from "@/components/device-drilldown";
import { type Device, type DeviceStatus, STATUS_COLOR, STATUS_LABEL } from "@/lib/types";
import { Activity, AlertTriangle, MapPin, Shield, Zap } from "lucide-react";

interface Fleet {
  title: string;
  disclaimer: string;
  n_devices: number;
  geographic_distribution: Record<string, number>;
  status_summary: Record<string, number>;
  replacement_queue_count: number;
  devices: Device[];
}

export function DashboardClient({ fleet }: { fleet: Fleet }) {
  const [filter, setFilter] = useState<"all" | DeviceStatus>("all");
  const [selectedDevice, setSelectedDevice] = useState<Device | null>(null);

  const filtered = useMemo(
    () => (filter === "all" ? fleet.devices : fleet.devices.filter((d) => d.status === filter)),
    [fleet.devices, filter],
  );

  const sohBuckets = useMemo(() => {
    const buckets = [
      { range: "≥95%", min: 0.95, max: 1.01, count: 0, color: "#34d399" },
      { range: "90–95%", min: 0.9, max: 0.95, count: 0, color: "#22d3ee" },
      { range: "85–90%", min: 0.85, max: 0.9, count: 0, color: "#a78bfa" },
      { range: "80–85%", min: 0.8, max: 0.85, count: 0, color: "#fbbf24" },
      { range: "<80%", min: 0, max: 0.8, count: 0, color: "#f87171" },
    ];
    for (const d of fleet.devices) {
      const b = buckets.find((b) => d.soh_lfp >= b.min && d.soh_lfp < b.max);
      if (b) b.count++;
    }
    return buckets;
  }, [fleet.devices]);

  // Most-urgent first: smallest RUL at the top, so row 1 is the device that
  // needs replacing soonest. Aligned with the Tier-1 status logic — anything
  // already flagged early_aging (SOH < 0.85 OR rul < 800) is on the queue.
  const replacementCandidates = useMemo(
    () =>
      fleet.devices
        .filter((d) => d.status === "early_aging")
        .sort((a, b) => a.rul_cycles - b.rul_cycles)
        .slice(0, 8),
    [fleet.devices],
  );

  return (
    <div className="space-y-10">
      {/* Fictional-persona banner — site names use real cloud-provider brands as
          illustrative personas only; no commercial relationship is implied. */}
      <div
        role="note"
        className="rounded-md border-l-4 border-red-500 bg-red-500/10 px-4 py-3 text-xs sm:text-sm text-foreground"
      >
        <div className="font-semibold text-red-400 uppercase tracking-wider mb-1">
          ⚠ Fictional demo — academic illustration only
        </div>
        <p className="leading-relaxed text-muted">
          All site names visible below (<span className="text-foreground">CoreWeave / Lambda /
          Equinix / Meta / Google / AWS / Microsoft / Digital Realty</span>) are used purely
          as <span className="text-foreground">illustrative personas</span> for the ATCC 2026
          academic demonstration. <span className="text-foreground font-medium">No
          commercial, customer, or endorsement relationship is implied or claimed.</span> Every
          device shown is generated by a seeded RNG simulator and bears the SIMULATED DATA
          watermark.
        </p>
      </div>

      <header className="flex flex-wrap items-start justify-between gap-4">
        <div className="space-y-3 min-w-0">
          <div className="text-xs uppercase tracking-[0.2em] text-muted">Fleet Health Dashboard</div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-semibold tracking-tight">{fleet.n_devices.toLocaleString()} Sysblade BBUs across the fleet</h1>
          <p className="text-sm sm:text-base text-muted max-w-3xl leading-relaxed">
            <span className="text-foreground font-medium">Three service tiers</span> visible side-by-side:{" "}
            <span className="text-foreground">real-time monitoring</span>,{" "}
            <span className="text-foreground">proactive maintenance</span> triggered by Battery Twin SOH inference,
            and <span className="text-foreground">predictive ops</span> surfacing replacement candidates before SOH crosses{" "}
            <span className="text-foreground font-medium">80 %</span>.
          </p>
        </div>
        <span className="rounded-md border border-warning/40 bg-warning/10 px-3 py-1.5 text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-warning whitespace-normal">
          ⚠ Simulated data · synthetic fleet for demo only
        </span>
      </header>

      {/* Tier 1 — real-time monitoring */}
      <section className="space-y-4">
        <SectionHeader icon={<Activity className="h-4 w-4" />} kicker="Tier 1" title="Real-time monitoring" />
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
          <Stat
            label="Total devices"
            value={fleet.n_devices.toLocaleString()}
            tone="primary"
            hint={`${fleet.geographic_distribution.Texas} TX · ${fleet.geographic_distribution.Virginia} VA · ${fleet.geographic_distribution.Other} other`}
          />
          <Stat
            label="Healthy"
            value={fleet.status_summary.healthy.toLocaleString()}
            unit={`/ ${fleet.n_devices}`}
            tone="success"
            hint={`${((fleet.status_summary.healthy / fleet.n_devices) * 100).toFixed(1)} % currently nominal`}
          />
          <Stat
            label="Thermal warn"
            value={fleet.status_summary.thermal_warn}
            tone="warning"
            hint="LIC > 60 °C or LFP > 45 °C"
          />
          <Stat
            label="Early aging"
            value={fleet.status_summary.early_aging}
            tone="danger"
            hint="SOH dropping faster than RUL model expects"
          />
        </div>
      </section>

      {/* Tier 2 — geographic + SOH bucket */}
      <section className="space-y-4">
        <SectionHeader icon={<MapPin className="h-4 w-4" />} kicker="Tier 2" title="Proactive maintenance · geographic and SOH view" />

        <div className="flex flex-wrap items-center gap-2 text-xs">
          <span className="text-muted mr-2">Filter:</span>
          {(["all", "healthy", "thermal_warn", "early_aging"] as const).map((s) => (
            <button
              key={s}
              onClick={() => setFilter(s)}
              className={
                filter === s
                  ? "rounded-md bg-primary px-3 py-1.5 font-medium text-primary-foreground"
                  : "rounded-md border border-border bg-surface/40 px-3 py-1.5 text-muted hover:text-foreground"
              }
            >
              {s === "all" ? `All (${fleet.n_devices})` : `${STATUS_LABEL[s]} (${fleet.status_summary[s] ?? 0})`}
            </button>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
          <Card className="lg:col-span-2 simulated-watermark">
            <CardHeader>
              <CardTitle>Geographic distribution · 1000-device fleet</CardTitle>
            </CardHeader>
            <CardBody>
              <USFleetMap devices={filtered} height={400} />
              <p className="text-xs text-muted mt-3">
                <span className="text-foreground">Click any city marker</span> to drill in;
                hover for status breakdown. Texas + Virginia clusters dominate per JLL YE-2025
                §C.1.
              </p>
            </CardBody>
          </Card>

          <Card className="simulated-watermark">
            <CardHeader>
              <CardTitle>SOH distribution</CardTitle>
            </CardHeader>
            <CardBody className="space-y-3">
              {sohBuckets.map((b) => (
                <div key={b.range}>
                  <div className="flex items-center justify-between text-xs mb-1">
                    <span className="font-medium" style={{ color: b.color }}>
                      {b.range}
                    </span>
                    <span className="tabular-nums text-muted">{b.count} devices</span>
                  </div>
                  <div className="h-2 rounded-full bg-surface overflow-hidden">
                    <div
                      className="h-full rounded-full"
                      style={{
                        width: `${(b.count / fleet.n_devices) * 100}%`,
                        background: b.color,
                      }}
                    />
                  </div>
                </div>
              ))}
              <div className="pt-3 mt-3 border-t border-border text-xs text-muted leading-relaxed space-y-2">
                <p>
                  Tier-3 queue rule: <span className="text-foreground">SOH &lt; 85 %</span> <em>or</em>{" "}
                  <span className="text-foreground">RUL &lt; 800 cycles</span>.
                </p>
                <Disclosure summary="What 800 cycles means in years">
                  BBU duty averages ~50 cycles/yr (v2.2 §B.2), so{" "}
                  <span className="text-foreground">RUL = 800 cycles</span> ≈ 16 years of BBU
                  service remaining. The 800-cycle threshold is the &ldquo;needs replacement
                  within ~16 years&rdquo; gate, not 800 days.
                </Disclosure>
                <Disclosure summary="Where rul_cycles, soh_lfp, soh_lic come from">
                  <span className="text-foreground">rul_cycles</span> per device is computed by
                  the same LSTM you saw on <span className="text-foreground">/twin</span> — each
                  device is matched to a PyBaMM-calibrated BBU-duty trajectory, the LSTM
                  predicts that trajectory&rsquo;s total cycle life, and we subtract the
                  device&rsquo;s elapsed cycles (age × 50 cycles/yr per v2.2 §B.2). One model
                  deployed across the fleet, not a separate decay heuristic.{" "}
                  <span className="text-foreground">soh_lfp</span> stays as the per-device
                  state. <span className="text-foreground">soh_lic</span> is datasheet-derived
                  (LIC ≥ 100,000 nominal cycles per JM Energy / Eaton XLR specs) — LIC public
                  cycling data is too scarce to train on, and BBU duty doesn&rsquo;t push LIC
                  near its limits (whitepaper §6.2).
                </Disclosure>
              </div>
            </CardBody>
          </Card>
        </div>
      </section>

      {/* Tier 3 — predictive ops */}
      <section className="space-y-4">
        <SectionHeader icon={<Shield className="h-4 w-4" />} kicker="Tier 3" title="Predictive ops · replacement queue" />
        <Card className="simulated-watermark">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              Most urgent 8 · sorted by lowest RUL first
            </CardTitle>
            <p className="text-[11px] text-muted mt-1.5">
              Click any row for SOH / RUL / thermal drilldown.
            </p>
          </CardHeader>
          <CardBody>
            {/* min-w forces overflow-x-auto to actually scroll on phone widths
                instead of letting the table squeeze its columns into illegible
                multi-line headers and clipped status badges. */}
            <div className="overflow-x-auto -mx-5 px-5">
              <table className="w-full text-sm min-w-[680px]">
                <thead>
                  <tr className="text-muted text-xs uppercase tracking-wider whitespace-nowrap">
                    <th className="text-left py-2 pr-3">Device</th>
                    <th className="text-left py-2 pr-3">Site</th>
                    <th className="text-right py-2 pr-3">SOH</th>
                    <th className="text-right py-2 pr-3">RUL (cycles)</th>
                    <th className="text-right py-2 pr-3">Age (mo)</th>
                    <th className="text-right py-2 pr-3">Temp LFP</th>
                    <th className="text-right py-2">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {replacementCandidates.length === 0 && (
                    <tr>
                      <td colSpan={7} className="py-6 text-center text-muted">
                        No urgent replacements — fleet is in good shape.
                      </td>
                    </tr>
                  )}
                  {replacementCandidates.map((d) => (
                    <tr
                      key={d.id}
                      onClick={() => setSelectedDevice(d)}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" || e.key === " ") {
                          e.preventDefault();
                          setSelectedDevice(d);
                        }
                      }}
                      tabIndex={0}
                      role="button"
                      aria-label={`Open drilldown for ${d.id} (${d.site})`}
                      className="cursor-pointer border-t border-border transition-colors hover:bg-surface/60 focus:bg-surface/60 focus:outline-none"
                    >
                      <td className="py-2.5 pr-3 font-mono text-xs whitespace-nowrap">{d.id}</td>
                      <td className="py-2.5 pr-3">
                        <div className="whitespace-nowrap">{d.site}</div>
                        <div className="text-xs text-muted whitespace-nowrap">{d.location}</div>
                      </td>
                      <td className="py-2.5 pr-3 text-right tabular-nums">{(d.soh_lfp * 100).toFixed(1)}%</td>
                      <td className="py-2.5 pr-3 text-right tabular-nums">{d.rul_cycles}</td>
                      <td className="py-2.5 pr-3 text-right tabular-nums">{d.age_months}</td>
                      <td className="py-2.5 pr-3 text-right tabular-nums">{d.temp_lfp_c}°C</td>
                      <td className="py-2.5 text-right">
                        <span
                          className="rounded-full px-2 py-0.5 text-xs font-medium whitespace-nowrap"
                          style={{ background: `${STATUS_COLOR[d.status]}20`, color: STATUS_COLOR[d.status] }}
                        >
                          {STATUS_LABEL[d.status]}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="text-xs text-muted mt-4 flex items-center gap-2">
              <AlertTriangle className="h-3.5 w-3.5 text-warning" />
              {fleet.replacement_queue_count} devices currently on the replacement queue (status =
              early_aging) — automatically registered into the customer&rsquo;s ServiceNow / Jira
              pipeline via webhook.
            </p>
          </CardBody>
        </Card>
      </section>

      {/* Footer disclaimer */}
      <Card>
        <CardBody className="text-xs text-muted leading-relaxed">
          <div className="flex items-center gap-2 text-warning font-medium mb-1">
            <Zap className="h-3.5 w-3.5" /> About this dashboard
          </div>
          <p>
            {fleet.disclaimer}{" "}
            <span className="text-foreground">RUL per device is computed by the same LSTM</span>{" "}
            shown on /twin — same model, two views.
          </p>
          <Disclosure summary="How the 1000 devices were generated" className="mt-2">
            Documented seeded RNG (<code className="text-foreground">scripts/generate_twin_scenarios.py</code>),
            weighted to Texas + Virginia per JLL YE-2025. Status, temperatures, and aging
            buckets reflect plausible field distributions but no production deployment exists
            yet. Each device is matched to a per-device PyBaMM-calibrated BBU-duty trajectory
            and the LSTM predicts its total cycle life.
          </Disclosure>
        </CardBody>
      </Card>

      {/* Per-device drilldown — renders only when a Tier-3 row is clicked. */}
      {selectedDevice && (
        <DeviceDrilldown
          device={selectedDevice}
          onClose={() => setSelectedDevice(null)}
        />
      )}
    </div>
  );
}

function SectionHeader({
  icon,
  kicker,
  title,
}: {
  icon: React.ReactNode;
  kicker: string;
  title: string;
}) {
  return (
    <div className="flex items-baseline gap-3 border-b border-border pb-2">
      <span className="inline-flex items-center gap-1.5 rounded-full bg-primary/15 text-primary px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider">
        {icon}
        {kicker}
      </span>
      <h2 className="text-lg font-semibold tracking-tight">{title}</h2>
    </div>
  );
}
